#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace SuspenseCoreEnemyTags
{
    namespace State
    {
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Patrol);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alert);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chase);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cover);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Retreat);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);
    }

    namespace Event
    {
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerDetected);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerLost);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageTaken);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReachedDestination);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TargetInRange);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TargetOutOfRange);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LowHealth);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AmmoEmpty);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PatrolComplete);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleTimeout);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Died);
    }

    namespace Type
    {
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scav);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PMC);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss);
        ENEMYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Raider);
    }
}
