// Copyright Suspense Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Interface.h"
#include "GameplayTagContainer.h"
#include "ISuspenseCoreWeaponUIWidget.generated.h"

// Forward declarations - только базовые UE типы
class AActor;
class USuspenseEventManager;

UINTERFACE(MinimalAPI, BlueprintType)
class USuspenseWeaponUIWidgetInterface : public UInterface
{
    GENERATED_BODY()
};

/**
 * Interface for weapon UI widgets
 * Provides standardized methods for weapon information display
 *
 * IMPORTANT: This interface is for UI widgets that DISPLAY weapon information.
 * Widgets implementing this interface should NOT broadcast events - they only receive and display data.
 * Events should be broadcast by weapon components that own the actual data.
 */
class BRIDGESYSTEM_API ISuspenseWeaponUIWidgetInterface
{
    GENERATED_BODY()

public:
    //================================================
    // Weapon Binding
    //================================================
    
    /**
     * Sets the weapon to display information for
     * @param Weapon Weapon actor to track
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void SetWeapon(AActor* Weapon);

    /**
     * Clears the current weapon
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void ClearWeapon();

    /**
     * Gets the currently tracked weapon
     * @return Current weapon or nullptr
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    AActor* GetWeapon() const;

    //================================================
    // Ammo Display
    //================================================
    
    /**
     * Updates ammo display
     * @param CurrentAmmo Current ammo in magazine
     * @param RemainingAmmo Remaining ammo in reserve
     * @param MagazineSize Magazine capacity
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void UpdateAmmoDisplay(float CurrentAmmo, float RemainingAmmo, float MagazineSize);

    /**
     * Sets ammo display format
     * @param Format Format string (e.g., "{0}/{1}")
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void SetAmmoDisplayFormat(const FString& Format);

    //================================================
    // Fire Mode Display
    //================================================
    
    /**
     * Updates fire mode display
     * @param FireModeTag Current fire mode tag
     * @param DisplayName Fire mode display name
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void UpdateFireMode(const FGameplayTag& FireModeTag, const FText& DisplayName);

    /**
     * Sets available fire modes
     * @param AvailableModes Array of available fire mode tags
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void SetAvailableFireModes(const TArray<FGameplayTag>& AvailableModes);

    //================================================
    // Weapon State Display
    //================================================
    
    /**
     * Shows reload indicator
     * @param ReloadTime Total reload time
     * @param ElapsedTime Time elapsed since reload started
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void ShowReloadIndicator(float ReloadTime, float ElapsedTime);

    /**
     * Hides reload indicator
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void HideReloadIndicator();

    /**
     * Updates weapon state indicator
     * @param StateTag Current weapon state tag
     * @param bIsActive Whether state is active
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "UI|Weapon")
    void UpdateWeaponState(const FGameplayTag& StateTag, bool bIsActive);

    //================================================
    // Static Helper Methods
    //================================================

    /**
     * Static helper to get event manager for widgets that need it
     * @param WorldContextObject Any object with valid world context
     * @return Event manager or nullptr
     */
    static USuspenseEventManager* GetDelegateManagerStatic(const UObject* WorldContextObject);

    // REMOVED: BroadcastAmmoUpdated - widgets should not broadcast events
    // Events should be generated by weapon components that own the actual data
};
